### PR TITLE
Examples overhaul

### PR DESCRIPTION
**Pull request by obackhouse**
This PR works towards overhauling the examples.

- Added a `catalogue` subdirectory to the `examples` directory which contains an appropriately named file giving an example of each possible method combination in the package. Note for the future that these are automatically generated but I won't leave that script in the git memory.

### CODE REVIEW

**Comment by ghb24** [comment]
I've pushed a few small changes to the comments. Other suggestions for improving examples:

 - I would move the examples out of a folder called 'advanced', unless you have plans to introduce a heirarchy of simple examples and more complex ones (though currently I don't think that there are enough examples to justify this).
- Indicate somewhere that the number of moments should be odd. I don't think this is currently mentioned anywhere?
- In the qsGW example, is the naux attribute not the number of poles in the self-energy, rather than the number of poles in the GF? Also, what is the 'as_perturbed_mo_energy' method? This doesn't seem to be described?
- Might be nice to have an example similar to 09 (or extend 09) for a UHF system where you plot the alpha and beta spectrum separately
- Would be nice to have an example for a custom hamiltonian, potentially both with and without k-points
- Other examples/additions to examples it might be nice to have:
-   Getting quasiparticle energies from a correlated G (e.g. scGW) after low-weighted poles have been removed (with given threshold?), as well as other quantities like a gap (potentially having removed low-weights)
- Getting other properties, e.g. energies from the GF, or 1RDMs / dipole moments
- Interpolation in k-space for PBC (did you remove this?)
- Different xc funcs - most/all results are for HF (which would generally be unusual for GW users outside the handful that do molecular systems)
- Example of increasing the accuracy, via increasing npoints for the numerical integration and the thresholds for compression, as well as the different options for the compression?
- 08 doesn't run for me: 
`  File "/Users/george/Code/momentGW/momentGW/thc.py", line 100, in transform
    Lp = lib.einsum("Lp,pq->Lq", self.coll, self.mo_coeff)
  File "/Users/george/Code/pyscf_boothgroup/pyscf/lib/numpy_helper.py", line 239, in einsum
    out = _contract(subscripts, *tensors, **kwargs)
  File "/Users/george/Code/pyscf_boothgroup/pyscf/lib/numpy_helper.py", line 111, in _contract
    return _numpy_einsum(idx_str, A, B)
  File "<__array_function__ internals>", line 180, in einsum
  File "/Users/george/opt/miniconda3/lib/python3.9/site-packages/numpy/core/einsumfunc.py", line 1359, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (32,4)->(32,newaxis,4) (19,19)->(19,19)`
- 09 doesn't run for me:
`Traceback (most recent call last):
  File "/Users/george/Code/momentGW/examples/advanced/09-spectral_functions.py", line 34, in <module>
    f_gw = gw.gf.on_grid(grid, eta=eta, ordering="advanced")
AttributeError: 'Lehmann' object has no attribute 'on_grid'`

**Comment by obackhouse** [comment]
> * I would move the examples out of a folder called 'advanced', unless you have plans to introduce a heirarchy of simple examples and more complex ones (though currently I don't think that there are enough examples to justify this).

Done

> * Indicate somewhere that the number of moments should be odd. I don't think this is currently mentioned anywhere?

Example 0 says this

> * In the qsGW example, is the naux attribute not the number of poles in the self-energy, rather than the number of poles in the GF? Also, what is the 'as_perturbed_mo_energy' method? This doesn't seem to be described?

No, that's `gf.naux` which is the number of poles in the `gf` object. `as_perturbed_mo_energy` is a `dyson.Lehmann` method but I will describe it.

> * Might be nice to have an example similar to 09 (or extend 09) for a UHF system where you plot the alpha and beta spectrum separately

Added in example 10

> * Would be nice to have an example for a custom hamiltonian, potentially both with and without k-points

Added a Hubbard model without k-points - setting up the CDERI sounds like a pain for one with k-points, I'll leave that for now

> * Getting quasiparticle energies from a correlated G (e.g. scGW) after low-weighted poles have been removed (with given threshold?), as well as other quantities like a gap (potentially having removed low-weights)
> * Getting other properties, e.g. energies from the GF, or 1RDMs / dipole moments

Added a properties example

> * Interpolation in k-space for PBC (did you remove this?)

Oops yeah... I can add it back, although it's still pretty uncertain whether it's recommended to generally use that functionality

> * Different xc funcs - most/all results are for HF (which would generally be unusual for GW users outside the handful that do molecular systems)

I've changed the solid example to be DFT, I think the `xc` parameter in PySCF should be quite self-explanatory 

> * Example of increasing the accuracy, via increasing npoints for the numerical integration and the thresholds for compression, as well as the different options for the compression?

Added in examples 14 and 15

> * 08 doesn't run for me:
>   `  File "/Users/george/Code/momentGW/momentGW/thc.py", line 100, in transform Lp = lib.einsum("Lp,pq->Lq", self.coll, self.mo_coeff) File "/Users/george/Code/pyscf_boothgroup/pyscf/lib/numpy_helper.py", line 239, in einsum out = _contract(subscripts, *tensors, **kwargs) File "/Users/george/Code/pyscf_boothgroup/pyscf/lib/numpy_helper.py", line 111, in _contract return _numpy_einsum(idx_str, A, B) File "<__array_function__ internals>", line 180, in einsum File "/Users/george/opt/miniconda3/lib/python3.9/site-packages/numpy/core/einsumfunc.py", line 1359, in einsum return c_einsum(*operands, **kwargs) ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (32,4)->(32,newaxis,4) (19,19)->(19,19)`

Accidentally changed the system forgetting it's no fully ab initio, fixed

> * 09 doesn't run for me:
>   `Traceback (most recent call last): File "/Users/george/Code/momentGW/examples/advanced/09-spectral_functions.py", line 34, in <module> f_gw = gw.gf.on_grid(grid, eta=eta, ordering="advanced") AttributeError: 'Lehmann' object has no attribute 'on_grid'`

Seems like a very outdated `dyson` to me

**Comment by obackhouse** [comment]
Waiting on https://github.com/pyscf/pyscf/issues/1879 so I can add a PBE example to example 3.

**Comment by obackhouse** [comment]
I've added a custom Hamiltonian example for solids - not pretty, but hopefully will be helpful for future hacking

**Comment by ghb24** [comment]
That is awesome. Thanks.

**Review by ghb24 — APPROVED** [review]

**Pull request merged**
