### PR TITLE
Tests maintenance

### PR DESCRIPTION
**Pull request by obackhouse**
Clean up some tests, and try to optimise their runtime which is getting a bit too long. Also can now install as `pip install .[mpi]` to install alongside `mpi4py`.

- [x] Add reporting of timings for tests
- [x] Lint tests and examples with `black` and `isort` (but not `flake8`, too restrictive)
- [x] Optimise test runtime
- [x] ~Add MPI tests~ sadly these are still hanging even with parallel HDF5 so i'll save this for another PR

### CODE REVIEW

**Comment by obackhouse** [comment]
Going forward, let's try to keep the unit tests to 10 mins in the CI runner. It's currently about that with this PR so maybe i'll cut a bit more down before we merge this

**Comment by obackhouse** [comment]
Note that https://github.com/BoothGroup/momentGW/pull/51/commits/96a232ca5b4c78f8847613f6cee77133b61ffad4 makes all gamma-point PBC calculations using the molecular solver force `store_full=True` in the integrals. This is because my workaround to make PySCF density fitting work with MPI for molecules doesn't work for gamma-point PBC density fitting objects.

I don't think the scope of gamma-point calculations done via the molecular solvers is large enough to warrant a more detailed solution, this would only be an issue if the memory footprint of the integrals was too high, which would require an absolutely massive unit cell that you could never do real k-point sampled solutions with anyway.

**Comment by obackhouse** [comment]
ugh the MPI tests are still not working all the time

**Comment by obackhouse** [comment]
Ok `h5py` is compiling with parallel supports. If the CI hangs again i'm just going to do the adult thing and blame pyscf and disable it

**Comment by mkakcl** [comment]
> Going forward, let's try to keep the unit tests to 10 mins in the CI runner. It's currently about that with this PR so maybe i'll cut a bit more down before we merge this

Something I will keep in mind for future PRs. Currently still at around 10 mins, for future reference.

**Review by mkakcl — APPROVED** [review]
Many small changes, but everything is running well. Nice to have the tests a bit shorter for future PRs. Feel free to merge.

**Pull request merged**
