### PR TITLE
Self-energy construction fixes

### PR DESCRIPTION
**Pull request by obackhouse**
Implements a more rigorous construction of the static self-energy.

- [x] Implements `Integrals.get_veff` methods (`vj - vk * 0.5` for RHF, `vj - vk` for UHF)
- [x] Fixes static self-energy for non-HF UKS input (side effect of above)

### CODE REVIEW

**Comment by obackhouse** [comment]
Ok the PBE qsGW tests were failing because the static self-energy was using the mean-field DM rather than the DM updated by the quasiparticle loop, so that was bugged, but wasn't an issue for HF which is all we've used so far.

**Comment by obackhouse** [comment]
THC with DFT has regressed a bit, because previously we were doing:
```
se_static = (dft.get_j() - thc.get_k() * 0.5)  - dft.get_veff()
````
whereas I'm now doing
```
se_static = (thc.get_j() - thc.get_k() * 0.5)  - dft.get_veff()
````

I'm not sure the correct way to do this: `dft.get_veff` will use `dft.get_j` so it seems like subtracting `dft.get_j` is correct, rather than introducing additional error due to THC in J? Or should I just throw this out of the window and write a function to calculate Vxc directly instead of inferring it from the different between Veff and Vhf? Thoughts @ghb24 ?

**Comment by ghb24** [comment]
So there obviously isn't a 'right' answer here, and both should be the same in the limit of a complete auxiliary space. H
However, I agree with you that I would expect
`se_static = (dft.get_j() - thc.get_k() * 0.5)  - dft.get_veff()`
to give a faster convergence wrt auxiliary space, as the J term will be correctly cancelled - I would use this one.

**Review by mkakcl — APPROVED** [review]
Good changes. Feel free to merge when ready.

**Pull request merged**
